added android tv icon support
react-native-tvos/config-tv pull request #22
Opened 2024-08-20 21:15 UTC by HADeveloper

2024-10-09 18:49 UTC, douglowder requested changes
Looks good! I added a couple of suggested changes in the Typescript doc comments.

It would also be great if you could add a description of the new plugin property in the README!

2024-10-09 18:49 UTC, douglowder commented on packages/config-tv/src/types.ts
> +   * If set, this should be a path to an existing PNG file appropriate for an Ancroid TV icon image.
```suggestion
   * If set, this should be a path to an existing PNG file appropriate for an Android TV icon image.
```

2024-10-09 18:49 UTC, douglowder commented on packages/config-tv/src/types.ts
> +   * The Android manifest will be modified to reference this image and the image will be copied into
```suggestion
   * The icon image will not be resized.
   * The Android manifest will be modified to reference this image and the image will be copied into
```

2024-10-09 21:37 UTC, HADeveloper commented
@douglowder I made the requested changes. Let me know if anything else needs to be updated. Thanks!

2024-10-10 02:23 UTC, douglowder approved these changes

2024-10-10 02:23 UTC, merged